#!/bin/sh

(python postpushr.py > /dev/null 2>&1) & sleep 1;
ps -ef | grep "python postpushr.py" | grep -v grep | awk '{print $2}' | xargs kill;

if [ "$?" -eq "0" ]; then
	exit 0;
else
	echo "Warning: Build Failing";
	exit 0;
fi