#!/bin/sh

(python postpushr.py > /dev/null 2>&1) & sleep 1;

c=$(ps -ef | grep "python" | grep "MHacks" | grep -v grep | awk '{print $2}' | wc -c);

if [ "$c" -ne "0" ]; then
	ps -ef | grep "python" | grep "MHacks" | grep -v grep | awk '{print $2}' | xargs kill;
	exit 0;
else
	echo "Fatal: Build Failing";
	exit 1;
fi